[package]
name = "mesh_network"
version = "0.1.0"
edition = "2021"

[dependencies]
ring = "0.16"
zerocopy = "0.6"
thiserror = "1.0"
bytes = "1.0"
tokio = { version = "1.0", features = ["full"] }
serde_json = "1.0"
hashbrown = "0.14"
heapless = "0.8"

[dev-dependencies]
tokio-test = "0.4"